name: Go

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2.5.0
    - name: Setup Go environment
      uses: actions/setup-go@v3.3.1
    - name: Run golangci-lint
      uses: golangci/golangci-lint-action@v3.3.0

